[package]
name = "rogue-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "WASM bindings for the rogue NLS predictor"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rogue-nls.workspace = true
rogue-blow-up.workspace = true
rogue-rogue.workspace = true
rogue-production.workspace = true
serde.workspace = true
serde-wasm-bindgen = "0.6"
wasm-bindgen.workspace = true
js-sys.workspace = true
console_error_panic_hook.workspace = true
getrandom.workspace = true

[features]
default = []
